<a href="https://colab.research.google.com/github/Krish1983/Training/blob/main/Practice_session_22nd_August_2022.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
def addition(num):
  return num+num



In [2]:
list1 = [1,2,3,4]

In [3]:
answer = map(addition,list1)

In [4]:
answer

In [5]:
list(answer)

[2, 4, 6, 8]

In [6]:
list1 

[1, 2, 3, 4]

In [7]:
list1 [0] = 'Asif'

In [8]:
list1

['Asif', 2, 3, 4]

In [9]:
def square_no(num):
  return num**2
  


In [10]:
list1 = [2,3,5,7,9]

In [11]:
answer = map(square_no,list1)

In [12]:
answer

In [13]:
list(answer)

[4, 9, 25, 49, 81]

In [14]:
greater_no2=lambda num1,num2: num1 if(num1>num2) else num2

In [15]:
greater_no2(10,12)

12

In [16]:
greater_no2(-1,-99)

-1

In [17]:
!pip3 install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [18]:
import numpy as np

In [19]:
list1=[1,3,5,10]
list2=[2,4,6,8]
list3=[2,3,5,7]


In [21]:
a= np.array([list1,list2,list3])

In [22]:
a

array([[ 1,  3,  5, 10],
       [ 2,  4,  6,  8],
       [ 2,  3,  5,  7]])

In [23]:
a.ndim

2

In [24]:
a.shape

(3, 4)

In [25]:
players = [(74, 180), (74, 215), (72, 210), (72, 210), (73, 188)]

AttributeError: ignored

In [28]:
np_players = np.array(players)

In [29]:
np_players

array([[ 74, 180],
       [ 74, 215],
       [ 72, 210],
       [ 72, 210],
       [ 73, 188]])

In [30]:
np_players.shape

(5, 2)

In [31]:
players_converted = np_players * [0.0254, 0.453592]

In [32]:
players_converted

array([[ 1.8796  , 81.64656 ],
       [ 1.8796  , 97.52228 ],
       [ 1.8288  , 95.25432 ],
       [ 1.8288  , 95.25432 ],
       [ 1.8542  , 85.275296]])

In [35]:
tall_players = players_converted[players_converted[:,0] > 1.85]

In [36]:
tall_players

array([[ 1.8796  , 81.64656 ],
       [ 1.8796  , 97.52228 ],
       [ 1.8542  , 85.275296]])